#pragma config(Motor,  port1,           rightFrontMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightBackMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightLowerMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           rightUpperMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           rightLiftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           leftFrontMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           leftBackMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftLowerMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftUpperMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          leftLiftMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
//left trigger - vertical lift
//right trigger - reverse 4 bar

while(1 == 1)
  {
    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[rightFrontMotor] = vexRT[Ch2];
    motor[rightBackMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[leftFrontMotor] = vexRT[Ch3];
    motor[leftBackMotor]  = vexRT[Ch3];
}
// Raise, lower or do not move arm
		if(vexRT[Btn8U] == 1)       	//If button 5U is pressed...
		{
			motor[leftUpperMotor] = 63;
			motor[leftLowerMotor] = 63;
			motor[rightUpperMotor] = 63;
			motor[rightLowerMotor] = 63;
		}
		else if(vexRT[Btn8D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[leftUpperMotor] = 0;
			motor[leftLowerMotor] = 0;
			motor[rightUpperMotor] = 0;
			motor[rightLowerMotor] = 0;
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[leftUpperMotor] = 20;
			motor[leftLowerMotor] = 20;
			motor[rightUpperMotor] = 20;
			motor[rightLowerMotor] = 20;
		}

// open close or stop linear lift motor
		if(vexRT[Btn5U] == 1)       	//If Button 6U is pressed...
		{
			motor[leftLiftMotor] = 63;  		//...close the gripper.
			motor[rightLiftMotor] = 63;
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 6D is pressed...
		{
			motor[leftLiftMotor] = -63;  		//...close the gripper.
			motor[rightLiftMotor] = -63;
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[leftLiftMotor] = 0;  		//...close the gripper.
			motor[rightLiftMotor] = 0;
		}
	}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	       